app:
  name: poc-fiber
  pgPoolMin: 5
  pgPoolMax: 5
  logFile: "poc-fiber.log"
  version: 1.0.0
  server:
    base: https://localhost
    port: 8101 
    context: poc-fiber
    api: api/v1
otel:
  endpoint: "localhost:4317"
vault:
  endpoint: "http://localhost:8200"  
  token: "dev-root-token"
  path: "dev-secrets"
  data: "creds"
redis:
  host: localhost
  port: 6379    
oauth2:
  issuer: "http://localhost:9000/application/o/poc-fiber/"

