app:
  name: poc-fiber
  pgUrl: "postgres://fiber_user:fiber_user@localhost:5432/poc-fiber?sslmode=disable"
  pgPoolMin: 5
  pgPoolMax: 5
  logFile: "poc-fiber.log"
  version: 1.0.0
  server:
    base: https://localhost
    port: 8101 
    context: poc-fiber
    api: api/v1
otel:
  endpoint: "localhost:4317"
redis:
  host: localhost
  port: 6379    
oauth2:
  clientId: "bdGSbNnajHzFcdicCSD51yi2F42KGQbTDm2WiVZB"
  clientSecret: "yCOmR4cO4AgAq6J2PhuxVLyqLDfEmzmjZ7i22gHDbgbAViRCfkxkYk3e322N9yFj2QRXkyQd0HRBx89g9q9BOvZ0pcU0f1ZkrQE1k2xI7hGJFdMgdc4Q98CmEvQL7pQA"
  issuer: "http://localhost:9000/application/o/poc-fiber/"
sql:
  tenants:
    findByCode: "select id,uuid,code,label from tenants where code=$1"
    findByUuid: "select id,uuid,code,label from tenants where uuid=$1"
    updateLabelByUuid: "update tenants set label:=$1 where uuid:=$2"
  organizations:
    create: "insert into organizations (tenants_id,uuid,code,label,type) values ($1,$2,$3,$4,$5) returning id"
    updateLabelByUuid: "update organizations set label:=$1 where uuid:=$2"
    findAllDisplay: "select id,tenants_id,uuid,code,label,type from organizations where tenants_id=$1"
    findByTenantAndUuid: "select id,tenants_id,uuid,code,label,type from organizations where tenants_id=$1 and uuid=$2"
    existsByCode: "select count(1) from code where code=$1"
  sectors:
    create: "insert into sectors (tenants_id,organizations_id,uuid,code,label,parent_id,has_parent,depth) values ($1,$2,$3,$4,$5,$6,$7,$8) returning id"
    findByTenantOrg: "select id,tenants_id,organizations_id,uuid,code,label,parent_id,has_parent,depth from sectors where tenants_id=$1 and organizations_id=$2"
    findByUuid: "select id,tenants_id,organizations_id,uuid,code,label,parent_id,has_parent,depth from sectors where uuid=$1"
  users:
    create: "insert into users (tenants_id,organizations_id,uuid,last_name,first_name,login,email) values($1,$2,$3,$4,$5,$6,$7) returning id"
    loginExists: "select count(1) from users where login=$1"
    emailExists: "select count(1) from users where email=$1"
    findAllByTenantAndOrg: "select id,tenants_id,organizations_id,uuid,last_name,first_name,login,email from users where tenants_id=$1 and organizations_id=$2"
