app:
  name: poc-fiber
  pgUrl: "postgres://fiber_user:fiber_user@localhost:5432/poc-fiber?sslmode=disable"
  pgPoolMin: 5
  pgPoolMax: 5
  logFile: "poc-fiber.log"
  version: 1.0.0
  server:
    base: https://localhost
    port: 8101 
    context: poc-fiber
    api: api/v1
otel:
  endpoint: "localhost:4317"
redis:
  host: localhost
  port: 6379    
oauth2:
  clientId: "bdGSbNnajHzFcdicCSD51yi2F42KGQbTDm2WiVZB"
  clientSecret: "yCOmR4cO4AgAq6J2PhuxVLyqLDfEmzmjZ7i22gHDbgbAViRCfkxkYk3e322N9yFj2QRXkyQd0HRBx89g9q9BOvZ0pcU0f1ZkrQE1k2xI7hGJFdMgdc4Q98CmEvQL7pQA"
  issuer: "http://localhost:9000/application/o/poc-fiber/"

